// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ4JMSOAWlxPJzIxEeOoAHdht1iiAkBz0',
    appId: '1:891879768012:web:40771de13fd3ff3c572769',
    messagingSenderId: '891879768012',
    projectId: 'first-29691',
    authDomain: 'first-29691.firebaseapp.com',
    storageBucket: 'first-29691.appspot.com',
    measurementId: 'G-L7GTRNCDFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCscj9msBstsVQ0q58imdHiCgBYYVm7MuQ',
    appId: '1:891879768012:android:c7303626966b6db9572769',
    messagingSenderId: '891879768012',
    projectId: 'first-29691',
    storageBucket: 'first-29691.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdvq2ysVQx9uXU_RQdCu3BTw0N05LF9oY',
    appId: '1:891879768012:ios:37299b6a97f4d754572769',
    messagingSenderId: '891879768012',
    projectId: 'first-29691',
    storageBucket: 'first-29691.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdvq2ysVQx9uXU_RQdCu3BTw0N05LF9oY',
    appId: '1:891879768012:ios:37299b6a97f4d754572769',
    messagingSenderId: '891879768012',
    projectId: 'first-29691',
    storageBucket: 'first-29691.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ4JMSOAWlxPJzIxEeOoAHdht1iiAkBz0',
    appId: '1:891879768012:web:ef97e2938cac4736572769',
    messagingSenderId: '891879768012',
    projectId: 'first-29691',
    authDomain: 'first-29691.firebaseapp.com',
    storageBucket: 'first-29691.appspot.com',
    measurementId: 'G-QFYXSWS3EE',
  );
}
